### ISSUE TITLE
Usage problem

### ISSUE THREAD

**Issue by teopost** [alfie-max/Publish#3]
If I execute this:

publish  -f
/bin/sh: None: command not found

Facebook
Invalid Fields

I have an error

**Comment by alfie-max** [comment]
When you do `publish -f`
It is supposed to open up an editor (system default) where you can input the message that has to be posted on Facebook.

OK, now what happened here is that you don't have a default editor set for your environment.

To solve the issue put `export EDITOR=vim` (you can replace `vim` with your preferred editor) in your bashrc or zshrc or ..rc file

**Comment by alfie-max** [comment]
But, i am sorry to inform you that in-spite of this you wont be able to use this application for sending messages to Facebook. 
I haven't got write permission for the Facebook application. so it isn't ready for public use yet.

I am planning to make this into a web application and hopping i would get Facebook's approval and required permissions then.

You can still use the twitter, email and blog(word press) channels.
If you try with Facebook, it will fail at authorization step.
